name: Shoar
description: Flutter Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  webview_flutter: ^4.4.2

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: lib/assets/fonts/Tajawal-Black.ttf
        - asset: lib/assets/fonts/Tajawal-Bold.ttf 
        - asset: lib/assets/fonts/Tajawal-ExtraBold.ttf 
        - asset: lib/assets/fonts/Tajawal-ExtraLight.ttf 
        - asset: lib/assets/fonts/Tajawal-Light.ttf 
        - asset: lib/assets/fonts/Tajawal-Medium.ttf 
        - asset: lib/assets/fonts/Tajawal-Regular.ttf
